package com.wvaviator.greenkeep.entities;

public enum GrassType {
    KENTUCKY_BLUEGRASS,
    TALL_FESCUE,
    RYEGRASS,
    FINE_FESCUE,
    BENTGRASS,
    BERMUDAGRASS,
    ST_AUGUSTINE,
    ZOYSIAGRASS,
    CENTIPEDEGRASS,
    DICHONDRA,
    OTHER_COOL_SEASON,
    OTHER_WARM_SEASON,
    MIXED_COOL_SEASON,
    MIXED_WARM_SEASON,
    NONE
}
