name: GreenKeep Continuous Integration

on:
  push:
    branches: [ development, main ]
  pull_request:
    branches: [ development, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test with Maven
        run: ./mvnw clean install

      - name: Start Application
        run: ./mvnw spring-boot:run -Dspring-boot.run.profiles=dev &
        shell: bash

      - name: Check Application Health
        run: |
          for i in {1..30}; do # timeout for 1 minute
              if curl --silent --fail localhost:8080/actuator/health | jq -e '.status == "UP"' > /dev/null; then
                  echo "Application is up"
                  exit 0
              else
                  echo "Check #$i unsuccessful, retrying in 2 seconds"
                  sleep 2
              fi
          done
          echo "Server did not start after 1 minute"
          exit 1
        env:
          SERVER_PORT: 8080
